# Generated by Django 6.0.8 on 2026-09-03 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0037_powersync_synced_ingredient_tables'),
        ('wger_india', '0003_indiaprofile_gym_days_dailygoalreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='source',
            field=models.CharField(blank=True, default='', help_text="Steps source: '', 'stepper', 'treadmill', 'walking', 'other'", max_length=20),
        ),
        migrations.AddField(
            model_name='indiaprofile',
            name='tracking_start',
            field=models.DateField(blank=True, help_text='First day with any logged data; days before it are not judged', null=True),
        ),
        migrations.AddField(
            model_name='indiaprofile',
            name='weekly_gym_target',
            field=models.PositiveIntegerField(default=3, help_text='Gym sessions per calendar week (Mon-Sun), on flexible days'),
        ),
        migrations.AlterField(
            model_name='indiaprofile',
            name='gym_days',
            field=models.CharField(default='0,2,4', help_text='DEPRECATED (kept for data compat): fixed gym weekdays, replaced by weekly_gym_target', max_length=20),
        ),
        migrations.CreateModel(
            name='IngredientMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_restaurant', models.BooleanField(default=False)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='india_meta', to='nutrition.ingredient')),
                ('owner', models.ForeignKey(blank=True, help_text="Personal variants rank first in this user's food search", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_variants', to='nutrition.ingredient')),
            ],
        ),
    ]
