# Generated by Django 6.0.8 on 2026-09-03 20:53

from django.conf import settings
from django.db import migrations, models


def merge_duplicate_steps(apps, schema_editor):
    """Collapse pre-existing duplicate steps rows (sum per user+day+source)"""
    ActivityLog = apps.get_model('wger_india', 'ActivityLog')
    seen = {}
    for row in ActivityLog.objects.filter(activity='steps').order_by('id'):
        key = (row.user_id, row.date, row.source)
        if key in seen:
            keeper = seen[key]
            keeper.steps = (keeper.steps or 0) + (row.steps or 0)
            keeper.kcal = (keeper.kcal or 0) + (row.kcal or 0)
            keeper.save()
            row.delete()
        else:
            seen[key] = row


class Migration(migrations.Migration):

    dependencies = [
        ('wger_india', '0004_activitylog_source_indiaprofile_tracking_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_steps, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='activitylog',
            constraint=models.UniqueConstraint(condition=models.Q(('activity', 'steps')), fields=('user', 'date', 'activity', 'source'), name='unique_steps_per_day_source'),
        ),
    ]
