# Generated by Django 6.0.8 on 2026-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wger_india', '0005_activitylog_unique_steps_per_day_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='incline_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Treadmill incline in percent', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Treadmill speed in km/h', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity',
            field=models.CharField(choices=[('volleyball', 'Volleyball'), ('stepper', 'Stepper'), ('steps', 'Steps'), ('treadmill', 'Treadmill')], max_length=20),
        ),
    ]
